cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    ab:
      email: ab@gmail.com
      first_name: Aa
      last_name: Bb
      logged_in: false
      password: $2b$12$yXQH98aq2fI38.dfzfDc6eNs1kByeMHyA1SK3W205gvrOvwq8WgOu
      password_hint: Aa12345!
      roles: null
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      first_name: John
      last_name: Smith
      logged_in: false
      password: $2b$12$PGteNdSV1f2Yfia8AxFWGeGCAjKc9eO/GXTtR7wHpShKC3KVIIoDG
      roles:
      - admin
      - editor
      - viewer
    jsmith1:
      email: jsmith1@gmail.com
      first_name: asdf
      last_name: asdf
      logged_in: false
      password: $2b$12$74xHESQ5MDKh5VdGemQim.pz/L0D20JhQBe0Jx4FV3Lk7h0wCLUhy
      password_hint: asdfasdf
      roles: null
    picion:
      email: picione@gmail.com
      first_name: picio
      last_name: picione
      logged_in: false
      password: $2b$12$llDyFBrEjjfVODQFWB/1Mup8pk5X0jP7/VUvf4UkJafBwVQr8ZoZ2
      password_hint: asfasdf
      roles: null
    picione:
      email: pirla@gmail.com
      first_name: pirla
      last_name: pirlone
      logged_in: false
      password: $2b$12$bfb8ORlNqSpCIHdL.EpTKu8E.FuEOf7wRYqMTUJk4N0T25qi8Bq4K
      password_hint: Aa12345!
      roles: null
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      first_name: Rebecca
      last_name: Briggs
      logged_in: false
      password: $2b$12$8qhPZ4HEWdd5fjk1lXDBeODN5jeoVRqZz3Yu2oGt4Mop9P/xTmKyq
      roles:
      - viewer
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - melsby@gmail.com
